name: Java CI

on:
  push:
    branches:
      - main  # Runs when code is pushed to main
  pull_request:
    branches:
      - main  # Runs on pull requests to main

jobs:
  build:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Gets your code

      - name: Cache Maven dependencies
        uses: actions/cache@v2  # Correct version for caching
        with:
          path: ~/.m2/repository  # Cache the Maven dependencies
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Key to uniquely identify the cache
          restore-keys: |
            ${{ runner.os }}-maven-  # Restore the cache even if the key changes slightly

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Eclipse Temurin JDK (recommended)
          java-version: '17'       # Use Java 17

      - name: Build with Maven
        run: mvn clean package -DskipTests  # Builds the project, skipping tests

      - name: Run Tests
        run: mvn test  # Runs unit tests
