trigger:
- '*'

pool:
  vmImage: 'ubuntu-20.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: JavaToolInstaller@0
  displayName: 'Install JDK 17'
  inputs:
    version: '17'
    jdkArchitecture: 'x64'

- task: Maven@3
  displayName: 'Restore dependencies'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean'

- task: Maven@3
  displayName: 'Build the project'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    options: '-DskipTests'

- task: Maven@3
  displayName: 'Run Tests'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'

- task: CopyFiles@2
  displayName: 'Copy JAR file to staging'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
